### ISSUE TITLE
compilation ?

### ISSUE THREAD

**Issue by StarForser** [usernameak/div_slashopt#1]
Hi, as I understand it, you need to compile the latest release yourself? You also need to compile winmm.dll?

**Comment by usernameak** [comment]
Oops, seems like I forgot to upload the file ;)

Will do that soon.

On the compilation, if you want to compile it yourself: winmm.dll is just renamed ASI loader from ThirteenAG (I renamed it so that it loads before the game's renderer DLL).

**Comment by usernameak** [comment]
Uploaded the file.
